const HardhatHero = () => (
  <svg
    width="140"
    height="140"
    viewBox="0 0 140 140"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g transform="translate(20, 10)">
      <ellipse
        cx="50"
        cy="48"
        rx="32"
        ry="28"
        fill="#9B59B6"
        stroke="#8E44AD"
        strokeWidth="3"
      />
      <rect
        x="20"
        y="48"
        width="60"
        height="8"
        fill="#8E44AD"
        rx="2"
      />
      <ellipse
        cx="50"
        cy="30"
        rx="28"
        ry="22"
        fill="#B57EDC"
      />
      <rect
        x="35"
        y="28"
        width="30"
        height="4"
        fill="#FFD700"
        rx="1"
      />
      <circle cx="40" cy="42" r="6" fill="#2C3E50" />
      <circle cx="60" cy="42" r="6" fill="#2C3E50" />
      <circle cx="41" cy="43" r="2" fill="#FFFFFF" />
      <circle cx="61" cy="43" r="2" fill="#FFFFFF" />
      <path
        d="M 40 52 Q 50 60 60 52"
        stroke="#2C3E50"
        strokeWidth="3"
        fill="none"
        strokeLinecap="round"
      />
      <line
        x1="15"
        y1="50"
        x2="0"
        y2="60"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <line
        x1="0"
        y1="60"
        x2="-5"
        y2="52"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <line
        x1="0"
        y1="60"
        x2="-5"
        y2="68"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <rect
        x="-10"
        y="55"
        width="8"
        height="12"
        fill="#95A5A6"
        stroke="#7F8C8D"
        strokeWidth="2"
        rx="1"
      />
      <line
        x1="-8"
        y1="58"
        x2="-4"
        y2="64"
        stroke="#7F8C8D"
        strokeWidth="1.5"
      />
      <line
        x1="-4"
        y1="58"
        x2="-8"
        y2="64"
        stroke="#7F8C8D"
        strokeWidth="1.5"
      />
      <line
        x1="85"
        y1="50"
        x2="100"
        y2="45"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <line
        x1="100"
        y1="45"
        x2="105"
        y2="52"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <circle
        cx="105"
        cy="52"
        r="10"
        fill="none"
        stroke="#8E44AD"
        strokeWidth="3"
      />
      <path
        d="M 100 52 L 103 55 L 110 48"
        stroke="#8E44AD"
        strokeWidth="3"
        fill="none"
        strokeLinecap="round"
      />
      <rect
        x="38"
        y="60"
        width="24"
        height="8"
        fill="#8E44AD"
        stroke="#7F4E9D"
        strokeWidth="2"
        rx="2"
      />
      <rect
        x="42"
        y="62"
        width="4"
        height="4"
        fill="#FFD700"
        rx="1"
      />
      <rect
        x="48"
        y="62"
        width="4"
        height="4"
        fill="#FFD700"
        rx="1"
      />
      <rect
        x="54"
        y="62"
        width="4"
        height="4"
        fill="#FFD700"
        rx="1"
      />
      <line
        x1="38"
        y1="73"
        x2="32"
        y2="95"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <line
        x1="62"
        y1="73"
        x2="68"
        y2="95"
        stroke="#8E44AD"
        strokeWidth="4"
        strokeLinecap="round"
      />
      <circle cx="32" cy="97" r="5" fill="#8E44AD" />
      <circle cx="68" cy="97" r="5" fill="#8E44AD" />
    </g>
  </svg>
);

export default HardhatHero;
